runtime: python312

instance_class: F1

entrypoint: gunicorn -b :$PORT app:app --timeout 120

env_variables:
  FLASK_ENV: "production"
  BYBIT_API_KEY: "GSUJ1MAAWbJ7qRU60b"
  BYBIT_API_SECRET: "GoXEAT3XuCudFEGjqZpNSvc01inMZYY2IbGk"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

handlers:
- url: /static
  static_dir: static
  expiration: "1h"
  
- url: /.*
  script: auto
