runtime: python312

instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: "production"
  # Add these manually with your actual keys:
  # BYBIT_API_KEY: "your_api_key_here"
  # BYBIT_API_SECRET: "your_api_secret_here"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
